version: "3.3"
services:
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_USER=sportmanager
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sportmanagement
    ports:
      - '5432:5432'
    expose:
      - 5432

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/sportmanagement
      - SPRING_DATASOURCE_USERNAME=sportmanager
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - psql-db